[web]
web-server ansible_host=52.53.166.121

[app]
app-server ansible_host=54.183.229.237

[db]
db-server ansible_host=54.219.111.77

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=../terra-ansible.pem

[application:children]
web
app

[all_servers:children]
application
db